package com.meridiangoods.requestpayment

import org.axonframework.eventsourcing.annotation.EventTag
import java.time.Instant
import java.util.UUID

/**
 * Event: Payment Requested. See `slices/request-payment.md`.
 *
 * Tagged with BOTH `orderId` (this slice's own idempotency entity, see
 * [RequestPaymentCommandHandler.State]) and `paymentId` (read by the `Record Payment Result`
 * slice's own entity, in a *different, independently-branched* PR, to validate INV-RPR-3 — see
 * that slice's doc, "Upstream events this slice relies on").
 *
 * IMPORTANT — cross-PR duplication judgment call (see the findings file
 * `w3-3-reactions.md`, "Judgment calls"): the two payments slices (`request-payment` and
 * `record-payment-result`) are two INDEPENDENT PRs per the engagement contract — neither
 * branches off the other. `record-payment-result` needs to event-source a check against this
 * exact type (fully-qualified name `com.meridiangoods.requestpayment.PaymentRequested`,
 * matching by the `paymentId` tag) *before* this PR has necessarily merged. Rather than
 * introduce a compile-time or runtime dependency between the two branches (impossible without
 * stacking them), this exact file is duplicated byte-for-byte into the `record-payment-result`
 * branch at the same path — both authored from this same `em export --slice request-payment`
 * field contract, so a future merge of both PRs converges on identical content at this path
 * with no conflict (the same category of acceptable cross-PR artifact as the build.gradle.kts
 * dependency-line note in the scaffold's own findings file). Do not edit this file without
 * mirroring the edit into `record-payment-result`'s copy, and vice versa.
 */
data class PaymentRequested(
    @EventTag(key = "orderId") val orderId: UUID,
    @EventTag(key = "paymentId") val paymentId: UUID,
    val amountCents: Int,
    val requestedAt: Instant,
)
